language: csharp
solution: SolidPrinciples.sln
install:
  - nuget restore SolidPrinciples.sln
  - nuget install xunit.runners -Version 1.9.2 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release SolidPrinciples.sln
  - mono ./testrunner/xunit.runners.1.9.2/tools/xunit.console.clr4.exe ./SolidPrinciples.Security.Clean.Tests/bin/Release/SolidPrinciples.Security.Clean.Tests.dll
  - mono ./testrunner/xunit.runners.1.9.2/tools/xunit.console.clr4.exe ./SolidPrinciples.Security.ExtraClean.Tests/bin/Release/SolidPrinciples.Security.ExtraClean.Tests.dll
  - mono ./testrunner/xunit.runners.1.9.2/tools/xunit.console.clr4.exe ./SolidPrinciples.Security.SuperClean.Tests/bin/Release/SolidPrinciples.Security.SuperClean.Tests.dll
